print ("Mad Libs")
print (" ")
noun1 = input("Tell me a noun (animal), and click enter. ")
noun2 = input("Tell me another noun (food - singular), and click enter. ")
noun3 = input("Tell me another noun, and click enter. ")
verb1 = input("Tell me a verb, and click enter. ")
verb2 = input("Tell me another verb, then click enter. ")
adjective1 = input("Tell me an adjective, and click enter. ")
proper_noun1 = input("Tell me a proper noun, and click enter. ")
noun4 = input("Tell me a noun (place), and click enter. ")
print (" ----------------------------------- ")
print ("If you give a " + noun1 + " a " + noun2 + "," )
print ("it is going to ask for a " + noun3 + ".")
print ("When you give it the " + noun3 + " it will want to " + verb1 + " - ")
print ("when it is done, it will " + verb2 + " and that is when " + adjective1 + " " + proper_noun1)
print ("will finally go to " + noun4 + ".")