
print ("Mario's Pizza Menu")
print ("-------------------")
print ("Extra Pepperoni Pizza - $8.00")
print ("    Ingredients: Pepperoni, cheese, sauce, and crust")
print ("Cheese Pizza - $5.00")
print ("    Ingredients: cheese, sauce, and crust")
print ("Breadsticks and Dip $3.00")
print ("    5 Breadsticks and maranara sauce")
print ("Hawaiian Special $9.00")
print ("    Ingredients: Canadian Bacon, pineapple, cheese, sauce, and crust")
print ("Meat Lover's Special $10.00")
print ("    Ingredients: Pepperoni, sausage, bacon, cheese, sauce, and crust")
print (" ")
print ("Large Soda Pop $1.75")
print ("Free refills while in location")